"""Generate canonical accent-stripping mappings from Python Unicode data.

Hangul is decomposed algorithmically at runtime. Compatibility transliteration
(for example oe for œ) is deliberately excluded.
"""
from pathlib import Path
import unicodedata as ud

out = [f'// Generated by scripts/generate_unicode_data.py; Unicode {ud.unidata_version}.',
       '// Canonical NFD decomposition with nonspacing marks removed.',
       'const canonicalWithoutAccents = <int, String>{']
for cp in range(0x110000):
    if 0xAC00 <= cp <= 0xD7A3:
        continue
    char = chr(cp)
    normalized = ''.join(c for c in ud.normalize('NFD', char) if ud.category(c) != 'Mn')
    if normalized != char:
        escaped = ''.join('\\u{%x}' % ord(c) for c in normalized)
        out.append(f"  0x{cp:x}: '{escaped}',")
out.append('};')
Path(__file__).resolve().parents[1].joinpath('lib/src/unicode_data.dart').write_text(
    '\n'.join(out) + '\n', encoding='utf-8')
